name: CI Backend

on:
  push:
    branches:
      - main
    paths:
      - "src/backend/**"
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Exoscale Container Registry
        run: echo  ${{ secrets.SECRET }}| docker login exo.container-registry.com -u "quentin.badoud@edufr.ch" --password-stdin

      - name: Construction de l'image Docker
        run: docker build -t exo.container-registry.com/c213-emf/todo-app:MCF -f src/backend/Dockerfile .

      - name: Push de l'image Docker
        run: docker push exo.container-registry.com/c213-emf/todo-app:MCF
